# Generated by Django 3.2.19 on 2023-07-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_proffileeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProffileeedItem',
            new_name='ProfilefeedItem',
        ),
    ]
